import { useEffect, useState } from 'react';
import { Feather, BookOpen, X } from 'lucide-react';
import type { Conversation } from '@new-ai-chat/contracts';
import { api } from './api.js';
import RecordHistory from './RecordHistory.js';
const tableNames:Record<string,string>={global_state:'全局状态',protagonist_info:'主角信息',important_characters:'重要角色',protagonist_skills:'主角技能',inventory:'背包物品',quests_events:'任务与事件',options:'选项'};
export default function Records({chat,version,activity,disabled,onError,onChanged,onClose}:{chat:Conversation;version:number;activity:any[];disabled:boolean;onError:(text:string)=>void;onChanged:()=>void;onClose:()=>void}) {
  const [tab,setTab]=useState('memory');const [memory,setMemory]=useState<any[]>([]);const [state,setState]=useState<any>({tables:{}});const [proposals,setProposals]=useState<any[]>([]);
  const [newMemory,setNewMemory]=useState('');const [stateText,setStateText]=useState('');const [editState,setEditState]=useState(false);const [busy,setBusy]=useState(false);
  const [baselineMemory,setBaselineMemory]=useState('');
  useEffect(()=>{let active=true;void Promise.all([api(`/conversations/${chat.id}/memory`),api(`/conversations/${chat.id}/state`),api(`/conversations/${chat.id}/proposals`)]).then(([m,s,p])=>{if(active){setMemory(m);setState(s);setStateText(JSON.stringify(s.tables,null,2));setProposals(p);}}).catch((error:Error)=>{if(active)onError(error.message);});return()=>{active=false;};},[chat.id,version]);
  async function run(path:string,value:unknown={}) {setBusy(true);try{await api(path,'POST',value);onChanged();}catch(error){onError((error as Error).message);}finally{setBusy(false);}}
  return <aside className="records"><header><div><span className="eyebrow">STORY NOTEBOOK</span><h2>故事记录</h2></div><button aria-label="关闭记录面板" onClick={onClose}><X size={17}/></button></header><nav>{[['memory','Memory'],['state','主角状态'],['planner','Agent']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id!)}>{label}</button>)}</nav><div className="records-content">
    {tab==='memory'&&<><div className="record-intro"><BookOpen size={21}/><h3>记住发生过的事</h3><p>每 {chat.memoryTurnInterval||'—'} 个完整回合记录一次。旁白与角色共同完成的一轮只计算一次。</p></div><button disabled={disabled||busy} onClick={()=>void run(`/conversations/${chat.id}/memory/generate`)}>{busy?'更新中…':'立即生成 Memory'}</button>{[...memory].reverse().map((entry)=><article className="memory-entry" key={entry.id}><span className="eyebrow">STAGE {entry.stage}</span><pre>{entry.content||'（空记忆标记）'}</pre></article>)}<details><summary>手动添加记录</summary><textarea aria-label="手动记忆" rows={5} value={newMemory} onChange={(e)=>setNewMemory(e.target.value)}/><button disabled={disabled||busy} onClick={()=>void run(`/conversations/${chat.id}/memory`,{content:newMemory}).then(()=>setNewMemory(''))}>保存记录</button></details></>}
    {tab==='memory'&&<details><summary>替换当前 Memory</summary><p>保存为新基线，旧快照仍可追溯。保存空内容可清空模型当前读取的记忆。</p><button onClick={()=>{const baseline=memory.findIndex(m=>m.source==='imported'||m.source==='manual');setBaselineMemory((baseline<0?memory:memory.slice(0,baseline+1)).reverse().map(m=>m.content).join('\n\n'));}}>载入当前记忆</button><textarea aria-label="替换记忆" value={baselineMemory} onChange={e=>setBaselineMemory(e.target.value)}/><button disabled={disabled||busy} onClick={()=>void run(`/conversations/${chat.id}/memory`,{content:baselineMemory,mode:'replace'})}>保存基线</button></details>}
    {tab==='state'&&<><div className="record-intro"><h3>此刻的世界</h3><p>当前事实、人物关系、物品与任务。详细经过保存在 Memory。</p></div><div className="two-col"><button disabled={disabled||busy} onClick={()=>void run(`/conversations/${chat.id}/state/generate`)}>AI 更新</button><button disabled={disabled||busy} onClick={()=>setEditState(!editState)}>编辑数据</button></div>{editState?<><textarea className="code state-editor" aria-label="状态 JSON" value={stateText} onChange={(e)=>setStateText(e.target.value)}/><button disabled={disabled||busy} onClick={()=>{try{void run(`/conversations/${chat.id}/state`,{tables:JSON.parse(stateText)});}catch(error){onError((error as Error).message);}}}>验证并保存</button></>:Object.entries(state.tables??{}).map(([table,rows])=><details className="state-table" key={table} open={table==='global_state'||table==='protagonist_info'}><summary>{tableNames[table]??table}<small>{(rows as any[]).length}</small></summary>{(rows as any[]).map((row,index)=><dl key={index}>{Object.entries(row).filter(([key])=>key!=='row_id').map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value??'—')||'—'}</dd></div>)}</dl>)}{!(rows as any[]).length&&<p className="muted">暂无记录</p>}</details>)}</>}
    {tab==='planner'&&<><div className="record-intro"><Feather size={23}/><h3>{chat.plannerEnabled?'Planner → Writer':'Writer 自动路由'}</h3><p>每轮最多两条输出。提案需手动应用，才会成为当前事实。</p></div>{proposals.map((p)=><article className="proposal" key={p.id}><small>{p.kind==='state'?'状态提案':'世界事件'} · {p.status}</small><pre>{JSON.stringify(p.payload,null,2)}</pre><div>{(p.status==='pending'?['apply','reject']:p.status==='applied'?['undo']:[]).map((action)=><button disabled={disabled||busy} key={action} onClick={()=>void run(`/proposals/${p.id}/${action}`)}>{{apply:'应用',reject:'拒绝',undo:'撤销'}[action]}</button>)}</div></article>)}<h4>本轮活动</h4>{activity.map((event,index)=><details className="activity" key={event.id??index}><summary>{event.type}</summary><pre>{JSON.stringify(event.payload,null,2)}</pre></details>)}{!activity.length&&<p className="muted">发送消息后，规划与工具活动会显示在这里。</p>}</>}
    <RecordHistory chatId={chat.id} tab={tab} version={version} disabled={disabled||busy} onChanged={onChanged} onError={onError}/>
  </div></aside>;
}
